// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salon.Shared;

#nullable disable

namespace Salon.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240626113159_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Salon.Shared.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("JenisKelamin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telepon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = "C-00001",
                            Alamat = "Bekasi",
                            JenisKelamin = (byte)2,
                            Nama = "Putri",
                            TanggalLahir = new DateTime(2000, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telepon = "0853 4677 3443"
                        },
                        new
                        {
                            Id = "C-00002",
                            Alamat = "Jakarta",
                            JenisKelamin = (byte)1,
                            Nama = "Andi",
                            TanggalLahir = new DateTime(1997, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telepon = "0833 5275 9486"
                        });
                });

            modelBuilder.Entity("Salon.Shared.Models.DetailLayanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdLayanan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdTransaksi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tarif")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdLayanan");

                    b.HasIndex("IdTransaksi");

                    b.ToTable("DetailLayanan");
                });

            modelBuilder.Entity("Salon.Shared.Models.DetailProduk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Harga")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdProduk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdTransaksi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Jumlah")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdProduk");

                    b.HasIndex("IdTransaksi");

                    b.ToTable("DetailProduk");
                });

            modelBuilder.Entity("Salon.Shared.Models.Layanan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tarif")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Layanan");

                    b.HasData(
                        new
                        {
                            Id = "L-001",
                            Nama = "Cukur",
                            Tarif = 23000
                        },
                        new
                        {
                            Id = "L-002",
                            Nama = "Smoothing",
                            Tarif = 150000
                        },
                        new
                        {
                            Id = "L-003",
                            Nama = "Coloring",
                            Tarif = 150000
                        },
                        new
                        {
                            Id = "L-004",
                            Nama = "Rebonding",
                            Tarif = 135000
                        },
                        new
                        {
                            Id = "L-005",
                            Nama = "Catok",
                            Tarif = 31000
                        },
                        new
                        {
                            Id = "L-006",
                            Nama = "Blow",
                            Tarif = 31000
                        },
                        new
                        {
                            Id = "L-007",
                            Nama = "Curly",
                            Tarif = 35000
                        });
                });

            modelBuilder.Entity("Salon.Shared.Models.Produk", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Harga")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Satuan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produk");

                    b.HasData(
                        new
                        {
                            Id = "P-0001",
                            Harga = 10000,
                            Nama = "Wardah",
                            Satuan = "Pcs"
                        },
                        new
                        {
                            Id = "P-0002",
                            Harga = 90000,
                            Nama = "Purbasari",
                            Satuan = "Pcs"
                        },
                        new
                        {
                            Id = "P-0003",
                            Harga = 20000,
                            Nama = "Bedak Lulur",
                            Satuan = "Botol"
                        },
                        new
                        {
                            Id = "P-0004",
                            Harga = 15000,
                            Nama = "Pemutih Wajah",
                            Satuan = "Cepuk"
                        },
                        new
                        {
                            Id = "P-0005",
                            Harga = 20000,
                            Nama = "Masker Wajah",
                            Satuan = "Botol"
                        },
                        new
                        {
                            Id = "P-0006",
                            Harga = 51000,
                            Nama = "Creambath",
                            Satuan = "Botol"
                        });
                });

            modelBuilder.Entity("Salon.Shared.Models.Transaksi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bayar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BiayaLayanan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BiayaProduk")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdCustomer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCustomer");

                    b.HasIndex("IdUser");

                    b.ToTable("Transaksi");
                });

            modelBuilder.Entity("Salon.Shared.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte>("JenisKelamin")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("JenisUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telepon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "Admin",
                            JenisKelamin = (byte)2,
                            JenisUser = (byte)0,
                            Nama = "Rosma Nelli",
                            Password = "3jqbFvenDDp2g3HTQ6ABlw==",
                            Telepon = "083665519043"
                        });
                });

            modelBuilder.Entity("Salon.Shared.Models.DetailLayanan", b =>
                {
                    b.HasOne("Salon.Shared.Models.Layanan", "Layanan")
                        .WithMany("DetailLayanan")
                        .HasForeignKey("IdLayanan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salon.Shared.Models.Transaksi", "Transaksi")
                        .WithMany("DetailLayanan")
                        .HasForeignKey("IdTransaksi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layanan");

                    b.Navigation("Transaksi");
                });

            modelBuilder.Entity("Salon.Shared.Models.DetailProduk", b =>
                {
                    b.HasOne("Salon.Shared.Models.Produk", "Produk")
                        .WithMany("DetailProduk")
                        .HasForeignKey("IdProduk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salon.Shared.Models.Transaksi", "Transaksi")
                        .WithMany("DetailProduk")
                        .HasForeignKey("IdTransaksi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produk");

                    b.Navigation("Transaksi");
                });

            modelBuilder.Entity("Salon.Shared.Models.Transaksi", b =>
                {
                    b.HasOne("Salon.Shared.Models.Customer", "Customer")
                        .WithMany("Transaksi")
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Salon.Shared.Models.User", "User")
                        .WithMany("Transaksi")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Salon.Shared.Models.Customer", b =>
                {
                    b.Navigation("Transaksi");
                });

            modelBuilder.Entity("Salon.Shared.Models.Layanan", b =>
                {
                    b.Navigation("DetailLayanan");
                });

            modelBuilder.Entity("Salon.Shared.Models.Produk", b =>
                {
                    b.Navigation("DetailProduk");
                });

            modelBuilder.Entity("Salon.Shared.Models.Transaksi", b =>
                {
                    b.Navigation("DetailLayanan");

                    b.Navigation("DetailProduk");
                });

            modelBuilder.Entity("Salon.Shared.Models.User", b =>
                {
                    b.Navigation("Transaksi");
                });
#pragma warning restore 612, 618
        }
    }
}
